FROM node:18-alpine3.15 

ENV MONGO_DB_USERNAME=admin \
    MONGO_DB_PWD=password

RUN mkdir -p /app

COPY ./backend /app

# set default dir so that next commands executes in /home/app dir
WORKDIR /app

# will execute npm install in /home/app because of WORKDIR
RUN npm install

# no need for /home/app/server.js because of WORKDIR
CMD ["node", "server.js"]
