FROM node:lts-alpine

RUN mkdir -p /app

COPY ./frontend /app

# set default dir so that next commands executes in /home/app dir
WORKDIR /app

# will execute npm install in /home/app because of WORKDIR
RUN npm install

CMD [ "npm", "run", "serve" ]
